### ISSUE TITLE
Mod incompatibility 

### ISSUE THREAD

**Issue by crunkazcanbe** [shift02/SextiarySector2#11]
Hey this I love your mods ,and I am English BTW ,but your mod does not act right when installed with other mod GalacticCraft mod here http://micdoodle8.com/mods/galacticraft/downloads

The innovatory tabs are on top of each other . look here http://joxi.ru/LmGe7RjiRRDE4A

Can you please fix ?

Thank you !

-Crunk

**Comment by crunkazcanbe** [comment]
I will fix this myself since nothing gets done when folks complain of issues . I downloaded the source and now have 4 other mods that add survival tabs working with this mod 100% compatible now . If any one wants the fixed mod let me know and I will give you a link . I also fixed a few crashes I was having ,and added in several null checks . :)

**Comment by shift02** [comment]
Thank you for the report.
 
This helps me very much !
 
I want to know the link of correction :D
