### ISSUE TITLE
Game Crash on startup / Mod Compability (BiblioWoods[Forestry][v1.7])

### ISSUE THREAD

**Issue by Nikslg** [shift02/SextiarySector2#12]
[crash-2015-11-30_16.44.15-client.txt](https://github.com/shift02/SextiarySector2/files/47324/crash-2015-11-30_16.44.15-client.txt)
Crash happens when BiblioWoods[Forestry][v1.7] is working at same time as SextiarySection2

**Comment by shift02** [comment]
Thank you for the report .

Please use the latest MCEconomy2
http://forum.minecraftuser.jp/viewtopic.php?f=13&t=17110&p=145963#p145962

**Comment by Nikslg** [comment]
But i do have last one:
MCEconomy2-2.5.0.b-1.7.0.jar
