### ISSUE TITLE
Errors in the Console 

### ISSUE THREAD

**Issue by crunkazcanbe** [shift02/SextiarySector2#15]
Here is the logs http://pastebin.com/nntBfvZc ,and this http://pastebin.com/jjFKvZE5 ,and one of the mods its conflicting with is here http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2260994-project-blue-1-1-6-a-project-red-add-on ,and the other is here http://ci.silvaniastudios.com:8080/job/HUDWidgets/ 

Thank you -Crunk :)

**Comment by shift02** [comment]
Thanks for the report.

It will be fixed in the next update.
