### ISSUE TITLE
“タブ”Tab be coverd when others mods added

### ISSUE THREAD

**Issue by MilkteaSoCold** [shift02/SextiarySector2#2]
The mods such as Tinker Contrust，Galaticraft and some other mods’ player tab have covered SS2’s tab.

**Comment by shift02** [comment]
Thank you for the report .
It is scheduled to be resolved in the next update .

![2015-01-18_22 51 25](https://cloud.githubusercontent.com/assets/6204699/5792628/9ff940e0-9f65-11e4-9545-b6864d3d8779.png)
